import{a as P,S,i as s}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const A="52255195-3e160ad4bb4ef956860251d45",M="https://pixabay.com/api/",R=15;async function u(t,o=1){if(typeof t!="string")throw new Error("Query must be a string");if(typeof o!="number")throw new Error("Page must be a number");const r={key:A,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:R};return(await P.get(M,{params:r})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){if(!Array.isArray(t)||t.length===0)return;const o=t.map(({webformatURL:r,largeImageURL:i,tags:e,likes:n,views:c,comments:E,downloads:v})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${r}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p>👍 ${n}</p>
          <p>👁 ${c}</p>
          <p>💬 ${E}</p>
          <p>⬇️ ${v}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),q.refresh()}function $(){f.innerHTML=""}function g(){h.classList.remove("hidden")}function m(){h.classList.add("hidden")}function L(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}const b=document.querySelector(".form"),B=document.querySelector(".load-more");let d="",a=1;const w=15;b.addEventListener("submit",O);B.addEventListener("click",_);async function O(t){t.preventDefault();const o=t.currentTarget.elements["search-text"].value.trim();if(!o){s.warning({title:"Attention",message:"Enter a search word!",position:"topRight"});return}d=o,a=1,$(),l(),g();try{const r=await u(d,a);if(!r.hits||r.hits.length===0){s.info({title:"Nothing found",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(r.hits);const i=Math.ceil(r.totalHits/w);a<i?L():(l(),s.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({title:"Error",message:"An error occurred while retrieving data.",position:"topRight"})}finally{m(),b.reset()}}async function _(){a+=1,g();try{const t=await u(d,a);if(t.hits&&t.hits.length>0){y(t.hits);const r=document.querySelector(".gallery .gallery-item");if(r){const{height:i}=r.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}const o=Math.ceil(t.totalHits/w);a>=o?(l(),s.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{s.error({title:"Error",message:"Could not load more images.",position:"topRight"})}finally{m()}}
//# sourceMappingURL=index.js.map
